version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/go:0-1.19-bullseye
    working_dir: /workspace
    volumes:
      - ../:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8080:8080
    networks:
      - local

networks:
  local: