groups:
  - name: app
    rules:
    - record: app:latency:99q:by_pattern
      expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_histogram_bucket[1m])) by (pattern, le))
      labels:
        service: app
    - record: app:rps:by_status
      expr: rate(http_requests_total[1m])
      labels:
        service: app
    - record: app:rps:5xx
      expr: rate(http_requests_total{status=~"5.."}[1m])
      labels:
        service: app
    - record: app:latency:99q:by_ms_pattern
      expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{pattern=~"/ms-.*"}[1m])) by (le, pattern))
      labels:
        service: app